/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectkonsep;

import projectkonsep.menu.Menu;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
//Menambahkan reminder 3 jam sebelum menyewa
/**
 *
 * @author Athma Farhan
 */
public final class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
        checkEnter();
        //txtusername.requestFocus();
        
    }
    void signIn() {
        String username;
        txtusername.requestFocus();
        username = txtusername.getText();
        
        String input = txtpassword.getText();
        

        if (username.compareTo("admin") == 0 && input.equals("AdminKonsep123")) {
            java.awt.EventQueue.invokeLater(() -> {
                new Menu().setVisible(true);
            });
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Kombinasi Username dan Password salah");
        }
    }
    
    public void checkEnter(){
        txtpassword.addKeyListener(new KeyAdapter()
    {
      public void keyPressed(KeyEvent e)
      {
        if (e.getKeyCode() == KeyEvent.VK_ENTER)
        {
          signIn();
        }
      }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlkiri = new javax.swing.JPanel();
        lbldeskripsi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlkanan = new javax.swing.JPanel();
        sprpassword = new javax.swing.JSeparator();
        txtpassword = new javax.swing.JPasswordField();
        lblpassword = new javax.swing.JLabel();
        sprusername = new javax.swing.JSeparator();
        txtusername = new javax.swing.JTextField();
        lblusername = new javax.swing.JLabel();
        lblkonsepstudio = new javax.swing.JLabel();
        lblsisfor = new javax.swing.JLabel();
        pnlsignin = new javax.swing.JPanel();
        lblsignin = new javax.swing.JLabel();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        pnlkiri.setBackground(new java.awt.Color(254, 0, 0));

        lbldeskripsi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbldeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        lbldeskripsi.setText("Studio Foto, Rental Kamera, Photobooth");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo-konsep.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout pnlkiriLayout = new javax.swing.GroupLayout(pnlkiri);
        pnlkiri.setLayout(pnlkiriLayout);
        pnlkiriLayout.setHorizontalGroup(
            pnlkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlkiriLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(pnlkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlkiriLayout.createSequentialGroup()
                        .addComponent(lbldeskripsi)
                        .addContainerGap())))
        );
        pnlkiriLayout.setVerticalGroup(
            pnlkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlkiriLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbldeskripsi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlkanan.setBackground(new java.awt.Color(255, 236, 237));

        sprpassword.setBackground(new java.awt.Color(0, 0, 0));
        sprpassword.setForeground(new java.awt.Color(0, 0, 0));

        txtpassword.setBackground(new java.awt.Color(240, 240, 240));
        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpasswordMouseClicked(evt);
            }
        });
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
        });

        lblpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblpassword.setText("Password");

        sprusername.setBackground(new java.awt.Color(0, 0, 0));
        sprusername.setForeground(new java.awt.Color(0, 0, 0));

        txtusername.setBackground(new java.awt.Color(240, 240, 240));
        txtusername.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtusername.setText("Masukkan Username anda");
        txtusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusernameMouseClicked(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });

        lblusername.setBackground(new java.awt.Color(53, 235, 202));
        lblusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblusername.setText("Username");

        lblkonsepstudio.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblkonsepstudio.setText("konsep.studio");

        lblsisfor.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lblsisfor.setText("Sistem Informasi");

        pnlsignin.setBackground(new java.awt.Color(51, 102, 255));
        pnlsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlsigninMouseClicked(evt);
            }
        });

        lblsignin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblsignin.setForeground(new java.awt.Color(255, 255, 255));
        lblsignin.setText("Sign In");

        javax.swing.GroupLayout pnlsigninLayout = new javax.swing.GroupLayout(pnlsignin);
        pnlsignin.setLayout(pnlsigninLayout);
        pnlsigninLayout.setHorizontalGroup(
            pnlsigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlsigninLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsignin)
                .addContainerGap())
        );
        pnlsigninLayout.setVerticalGroup(
            pnlsigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblsignin, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        button1.setActionCommand("SignIn");
        button1.setBackground(new java.awt.Color(51, 102, 255));
        button1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("SignIn");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlkananLayout = new javax.swing.GroupLayout(pnlkanan);
        pnlkanan.setLayout(pnlkananLayout);
        pnlkananLayout.setHorizontalGroup(
            pnlkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlkananLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblkonsepstudio)
                        .addComponent(lblsisfor)
                        .addComponent(lblpassword)
                        .addComponent(lblusername)
                        .addGroup(pnlkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sprpassword)
                            .addComponent(sprusername)
                            .addComponent(txtusername)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlsignin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        pnlkananLayout.setVerticalGroup(
            pnlkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlkananLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblsisfor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblkonsepstudio)
                .addGap(105, 105, 105)
                .addComponent(lblusername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sprusername, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblpassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sprpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(pnlsignin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlkiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlkanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlkiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlkanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        requestFocus();
    }//GEN-LAST:event_txtusernameActionPerformed

    private void pnlsigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlsigninMouseClicked
        signIn();
    }//GEN-LAST:event_pnlsigninMouseClicked

    private void txtusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseClicked
       txtusername.setText("");
       
    }//GEN-LAST:event_txtusernameMouseClicked

    private void txtpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseClicked
        txtpassword.setText("");
    }//GEN-LAST:event_txtpasswordMouseClicked

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        requestFocus();
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbldeskripsi;
    private javax.swing.JLabel lblkonsepstudio;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblsignin;
    private javax.swing.JLabel lblsisfor;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPanel pnlkanan;
    private javax.swing.JPanel pnlkiri;
    private javax.swing.JPanel pnlsignin;
    private javax.swing.JSeparator sprpassword;
    private javax.swing.JSeparator sprusername;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
